sudo: required
services:
  - docker

before_install:
  - dokcer build -t mohanaditya/docker_react -f Dockerfile.dev .

script:
  - docker run mohanaditya/docker_react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker_env"
  bucket_name: "elasticbeanstalk-us-west-2-30762772"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
