version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/JhaMohan/docker_react/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          docker build -t mohanaditya/docker_react -f Dockerfile.dev .
          docker run mohanaditya/docker_react npm run test -- --coverage

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
