version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t mohanaditya/docker_react -f Dockerfile.dev .
          docker run mohanaditya/docker_react npm run test -- --coverage
