version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: dokcer build -t mohanaditya/docker_react -f Dockerfile.dev .
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: docker run mohanaditya/docker_react npm run test -- --coverage
